#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Local Agent v0.1 的确定性 Planner。

Planner 不调用大模型，也不读取或修改 PDB。
它只根据已经结构化的 UserRequest：

1. 检查必要信息是否齐全；
2. 生成缺失信息清单；
3. 生成经过 ProjectConfig 验证的配置预览；
4. 生成固定、安全、可审核的工作流步骤；
5. 永远不自动执行科学任务。

大模型以后只负责把自然语言转换成 UserRequest。
实际工作流规则由本模块控制，避免模型任意发挥。
"""

from __future__ import annotations

from typing import Any

from protein_design_agent.public_identity import (
    PROJECT_NAME,
)
from protein_design_agent.schemas.agent_models import (
    AgentPlan,
    PlanStep,
    UserRequest,
)
from protein_design_agent.schemas.project_config import (
    ProjectConfig,
)


MISSING_FIELD_QUESTIONS: dict[str, str] = {
    "input_dir": "需要处理的 PDB 文件夹路径是什么？",
    "input_layout": (
        "PDB 已经正确分成 target/binder 多条链，"
        "还是 target 与 binder 拼接在同一条链？"
    ),
    "binder_chain": (
        "已经分链的数据中，哪一条链是 binder？"
    ),
    "source_chain": (
        "单链拼接结构位于哪一条原始链？"
    ),
    "target_residue_count": (
        "单链拼接结构中，前多少个残基属于 target？"
    ),
    "distinct_normalized_chain_ids": (
        "标准化后的 target 链和 binder 链不能相同，"
        "请指定两个不同链名。"
    ),
    "desired_regions_or_hotspots": (
        "constraint 模式必须提供 desired region "
        "或 hotspot。"
    ),
    "region_filter_soft_or_strict": (
        "constraint 模式下，请选择 soft 或 strict "
        "region 过滤。"
    ),
}


def questions_for_missing_fields(
    missing_fields: list[str],
) -> list[str]:
    """将机器字段名转换为可向用户提出的问题。"""
    return [
        MISSING_FIELD_QUESTIONS.get(
            field,
            f"请补充参数：{field}",
        )
        for field in missing_fields
    ]


def build_config_preview(
    request: UserRequest,
) -> dict[str, Any]:
    """
    将完整 UserRequest 转换为合法 ProjectConfig。

    调用本函数前必须确认 required_missing_fields() 为空。
    """
    missing = request.required_missing_fields()

    if missing:
        raise ValueError(
            "请求信息不完整，不能生成配置："
            f"{missing}"
        )

    assert request.input_dir is not None
    assert request.input_layout is not None

    project_name = (
        request.project_name
        or "protein_design_job"
    )

    input_config: dict[str, Any] = {
        "pdb_dir": request.input_dir,
        "recursive": False,
        "layout": request.input_layout,
    }

    if request.input_layout == "existing_chains":
        input_config.update(
            {
                "binder_chain": request.binder_chain,
                "target_chains": request.target_chains,
            }
        )
    else:
        input_config.update(
            {
                "source_chain": request.source_chain,
                "target_residue_count": (
                    request.target_residue_count
                ),
                "target_start_residue": (
                    request.target_start_residue
                ),
                "normalized_target_chain": (
                    request.normalized_target_chain
                ),
                "normalized_binder_chain": (
                    request.normalized_binder_chain
                ),
            }
        )

    preview: dict[str, Any] = {
        "schema_version": "0.1",
        "project_name": project_name,
        "description": (
            f"Generated by {PROJECT_NAME} "
            "Local Planner v0.1"
        ),
        "input": input_config,
        "regions": {
            "desired": request.desired_regions,
            "undesired": request.undesired_regions,
            "hotspots": request.hotspots,
            "hotspot_expand_radius": 8.0,
        },
        "ranking": {
            "ranker_version": "v0.1-expert",
            "region_policy": request.region_policy,
            "region_filter": request.region_filter,
            "top_k_report": request.requested_top_k,
            "top_n_sheets": 500,
        },
        "safety": {
            "unknown_situation": "stop",
            "allow_overwrite": False,
            "max_files": None,
        },
    }

    # 使用正式项目模型再次验证。
    # Planner 生成无效配置时立即暴露，而不是留到运行时。
    validated = ProjectConfig.model_validate(preview)

    return validated.model_dump(mode="json")


def ready_steps() -> list[PlanStep]:
    """生成固定的骨架排名准备流程。"""
    return [
        PlanStep(
            step_id="inspect_dataset",
            tool_name="inspect_pdb_dataset",
            description=(
                "只读检查 PDB 数量、链、残基编号、"
                "多模型和格式一致性。"
            ),
            status="READY",
        ),
        PlanStep(
            step_id="validate_input",
            tool_name="check_project_input",
            description=(
                "对照用户配置与实际 PDB，"
                "存在冲突时阻止继续。"
            ),
            status="READY",
        ),
        PlanStep(
            step_id="normalize_dataset",
            tool_name="normalize_pdb_dataset",
            description=(
                "在新目录中复制或拆分 PDB，"
                "绝不修改原始文件。"
            ),
            status="READY",
        ),
        PlanStep(
            step_id="validate_normalized_dataset",
            tool_name="validate_ranker_input",
            description=(
                "复查标准化结果是否具备明确的 "
                "target 和 binder。"
            ),
            status="READY",
        ),
        PlanStep(
            step_id="prepare_binderranker",
            tool_name="run_binderranker",
            description=(
                "校验冻结 Ranker 版本并生成 dry-run "
                "执行计划，不真正运行。"
            ),
            requires_approval=True,
            status="READY",
        ),
    ]


def build_agent_plan(
    request: UserRequest,
) -> AgentPlan:
    """根据 UserRequest 构建安全计划。"""
    missing = request.required_missing_fields()

    warnings: list[str] = []

    if request.project_name is None:
        warnings.append(
            "用户未提供 project_name，计划中暂时使用 "
            "protein_design_job；这不属于科学参数。"
        )

    if request.execute_requested:
        warnings.append(
            "用户提出了执行要求，但 Local Agent v0.1 "
            "只允许生成和审核计划，不会自动执行。"
        )

    if request.region_policy == "diagnostic":
        warnings.append(
            "diagnostic 模式会计算 region/hotspot 指标，"
            "但不改变 BinderRanker 默认主分和候选池过滤。"
        )

    if missing:
        questions = questions_for_missing_fields(missing)

        return AgentPlan(
            status="NEEDS_INFORMATION",
            request=request,
            missing_information=missing,
            warnings=warnings + questions,
            steps=[
                PlanStep(
                    step_id="collect_missing_information",
                    tool_name="ask_user",
                    description=(
                        "向用户询问缺失的必要参数，"
                        "不得根据猜测补全。"
                    ),
                    status="BLOCKED",
                )
            ],
            config_preview=None,
            execution_allowed=False,
        )

    config_preview = build_config_preview(request)

    return AgentPlan(
        status="READY_FOR_REVIEW",
        request=request,
        missing_information=[],
        warnings=warnings,
        steps=ready_steps(),
        config_preview=config_preview,
        execution_allowed=False,
    )
